import {parameterLines} from './parameter-labels.js?v=transformer-rx3';
import {EditorState} from './history.js?v=transformer-rx3';
import {catalog,portDomain} from '../components/catalog.js?v=transformer-rx3';
import {createComponent} from '../project/model.js?v=transformer-rx3';
import {symbol,terminalPosition,localPort,escapeHtml as esc} from './symbols.js?v=transformer-rx3';
// Interaction migration: Branch Builder 661856b, connectTerminals, renderWires,
// snappedWireMid, toSvgPoint, anchored zoom, pointer drag/marquee, copy/history.
export class Editor {
 constructor(canvas,project,onChange,onSelect,onStatus){this.canvas=canvas;this.state=new EditorState(project);this.onChange=onChange;this.onSelect=onSelect;this.onStatus=onStatus;this.tool='select';this.pendingTerminal=null;this.result=null;this.bind();this.render();}
 get project(){return this.state.project;}
 setProject(p){this.state=new EditorState(p);this.pendingTerminal=null;this.result=null;this.render();this.onSelect(null);this.onChange();}
 changed(){this.result=null;this.pendingTerminal=null;this.render();this.onChange();}
 select(id){this.state.selectedIds=id?[id]:[];this.state.selectedWireId=null;this.render();this.onSelect(this.project.components.find(c=>c.id===id)||null);}
 focus(id){const c=this.project.components.find(c=>c.id===id);if(!c)return;this.project.editor.viewCenter={x:c.x,y:c.y};this.select(id);}
 setTool(tool){this.tool=tool;this.pendingTerminal=null;this.render();this.onStatus(tool==='wire'?'依次点击两个端口连接；AC 与 DC 端口不可混接。':catalog[tool]?'点击画布放置 '+catalog[tool].label:'拖动移动 · Shift 多选 · 空白处框选 · 滚轮缩放');}
 // Original SVG coordinate conversion retained.
 toSvgPoint(event){const point=this.canvas.createSVGPoint();point.x=event.clientX;point.y=event.clientY;return point.matrixTransform(this.canvas.getScreenCTM().inverse());}
 add(type,point){this.state.checkpoint();const c=createComponent(type,this.state.id(),point.x,point.y);if(type==='source')c.parametersSI.frequencyHz=this.project.frequencyHz;this.project.components.push(c);this.state.selectedIds=[c.id];this.tool='select';this.changed();this.onSelect(c);}
 connectTerminals(from,to){if(from===to){this.pendingTerminal=null;this.render();return;}if(!portDomain(this.project,from)||portDomain(this.project,from)!==portDomain(this.project,to)){this.onStatus('连接失败：AC/DC 端口不能混接。');this.pendingTerminal=null;this.render();return;}const exists=this.project.wires.some(w=>(w.from===from&&w.to===to)||(w.from===to&&w.to===from));if(!exists){this.state.checkpoint();this.project.wires.push({id:this.state.id('W'),from,to,mid:null});this.changed();}this.pendingTerminal=null;this.render();}
 endpoint(key){const [id,side]=key.split('.');const c=this.project.components.find(c=>c.id===id);return c?terminalPosition(c,side):null;}
 snappedWireMid(wire,mid){const a=this.endpoint(wire.from),b=this.endpoint(wire.to),p={...mid};if(Math.abs(p.y-a.y)<=12&&Math.abs(p.y-b.y)<=12)p.y=Math.abs(p.y-a.y)<=Math.abs(p.y-b.y)?a.y:b.y;if(Math.abs(p.x-a.x)<=12&&Math.abs(p.x-b.x)<=12)p.x=Math.abs(p.x-a.x)<=Math.abs(p.x-b.x)?a.x:b.x;return p;}
 setZoom(value,point){const e=this.project.editor,old=e.zoom,z=Math.max(.2,Math.min(4,value));if(point){const k=old/z;e.viewCenter={x:point.x+(e.viewCenter.x-point.x)*k,y:point.y+(e.viewCenter.y-point.y)*k};}e.zoom=z;this.render();}
 fit(){const cs=this.project.components;if(!cs.length){this.project.editor={zoom:1,viewCenter:{x:600,y:350}};this.render();return;}const xs=cs.map(c=>c.x),ys=cs.map(c=>c.y);const width=Math.max(...xs)-Math.min(...xs)+260,height=Math.max(...cs.map(c=>c.y+72+parameterLines(c,this.project.frequencyHz).length*20))-Math.min(...ys)+140;this.project.editor.viewCenter={x:(Math.max(...xs)+Math.min(...xs))/2,y:(Math.max(...cs.map(c=>c.y+72+parameterLines(c,this.project.frequencyHz).length*20))+Math.min(...ys)-70)/2};const aspect=this.canvas.clientHeight/Math.max(1,this.canvas.clientWidth);this.project.editor.zoom=Math.max(.2,Math.min(1.35,1200/width,1200*aspect/height));this.render();}
 action(name){if(name==='copy'){this.state.copy();this.onStatus('已复制所选元件及内部导线。');return;}if(name==='rotate'&&this.state.selectedIds.length){this.state.checkpoint();for(const c of this.project.components)if(this.state.selectedIds.includes(c.id))c.rotation=((c.rotation||0)+90)%360;}else if(['undo','redo','paste','delete'].includes(name))this.state[name]();this.changed();this.onSelect(this.project.components.find(c=>c.id===this.state.selectedIds[0])||null);}
 render(){const e=this.project.editor||(this.project.editor={zoom:1,viewCenter:{x:600,y:350}}),width=1200/e.zoom,height=width*this.canvas.clientHeight/Math.max(1,this.canvas.clientWidth);this.canvas.setAttribute('viewBox',`${e.viewCenter.x-width/2} ${e.viewCenter.y-height/2} ${width} ${height}`);const high=new Set(this.result?.upstreamComponentIds||[]),wHigh=new Set(this.result?.upstreamWireIds||[]);let wires='';
 for(const w of this.project.wires){const a=this.endpoint(w.from),b=this.endpoint(w.to);if(!a||!b)continue;const mid=this.snappedWireMid(w,w.mid||{x:(a.x+b.x)/2,y:(a.y+b.y)/2});wires+=`<path class="wire ${wHigh.has(w.id)?'active-path':''} ${this.state.selectedWireId===w.id?'selected':''}" data-wire="${esc(w.id)}" d="M${a.x} ${a.y} L${mid.x} ${mid.y} L${b.x} ${b.y}"/>`;if(this.state.selectedWireId===w.id)wires+=`<circle class="wire-handle" data-handle="${esc(w.id)}" cx="${mid.x}" cy="${mid.y}" r="7"/>`;}
 const components=this.project.components.map(c=>{const selected=this.state.selectedIds.includes(c.id),p=c.parametersSI,labels=parameterLines(c,this.project.frequencyHz);
 return `<g class="component ${selected?'selected':''} ${high.has(c.id)?'active-path':''} ${c.type}" data-component="${esc(c.id)}" transform="translate(${c.x},${c.y})"><rect class="hitbox" x="-73" y="-49" width="146" height="99" rx="12"/><g class="symbol" transform="rotate(${c.rotation||0})">${symbol(c.type)}${Object.entries(catalog[c.type].ports).map(([side,domain])=>{const q=localPort(c.type,side),key=c.id+'.'+side;return `<circle class="terminal ${domain} ${this.pendingTerminal===key?'pending':''}" data-terminal="${esc(key)}" cx="${q.x}" cy="${q.y}" r="6"><title>${esc(side)} · ${domain.toUpperCase()}</title></circle>`;}).join('')}</g><text class="component-name" text-anchor="middle" y="-59">${esc(c.name)}</text><text class="component-detail" text-anchor="middle">${labels.map((line,i)=>`<tspan x="0" y="${72+i*20}">${esc(line)}</tspan>`).join('')}</text>${c.type==='bus'&&p.isPcc?'<text class="pcc-tag" x="13" y="-24">PCC</text>':''}${['gfl','gfm'].includes(c.type)?`<text class="inverter-tag" y="-37" text-anchor="middle">${c.type.toUpperCase()}</text>`:''}</g>`;}).join('');
 let marquee='';if(this.marquee){const a=this.marquee.start,b=this.marquee.current;marquee=`<rect class="marquee" x="${Math.min(a.x,b.x)}" y="${Math.min(a.y,b.y)}" width="${Math.abs(a.x-b.x)}" height="${Math.abs(a.y-b.y)}"/>`;}
 this.canvas.innerHTML=`<defs><pattern id="dots" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#ccd6db"/></pattern></defs><rect class="canvas-bg" x="${e.viewCenter.x-width/2}" y="${e.viewCenter.y-height/2}" width="${width}" height="${height}" fill="url(#dots)"/>${wires}${components}${marquee}`;
 document.getElementById('zoomValue').textContent=Math.round(e.zoom*100)+'%';document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===this.tool));
 }
 bind(){const canvas=this.canvas;
 const finishPointer=(cancelled=false)=>{
  if(this.pointerId==null)return;
  const pointerId=this.pointerId;this.pointerId=null;
  let dirty=false;
  if(this.marquee&&!cancelled){const a=this.marquee.start,b=this.marquee.current,ids=this.marquee.add?new Set(this.state.selectedIds):new Set();for(const c of this.project.components)if(c.x>=Math.min(a.x,b.x)&&c.x<=Math.max(a.x,b.x)&&c.y>=Math.min(a.y,b.y)&&c.y<=Math.max(a.y,b.y))ids.add(c.id);this.state.selectedIds=[...ids];this.onSelect(this.project.components.find(c=>c.id===this.state.selectedIds[0])||null);}
  if(this.drag?.saved){if(!cancelled)this.autoGlue();dirty=true;}
  if(this.wireDrag)dirty=true;
  this.drag=null;this.wireDrag=null;this.pan=null;this.marquee=null;
  if(canvas.hasPointerCapture?.(pointerId))canvas.releasePointerCapture(pointerId);
  if(dirty)this.changed();else this.render();
 };
 const beginPointer=event=>{this.pointerId=event.pointerId;this.pointerButtons=event.button===1?4:1;canvas.setPointerCapture?.(event.pointerId);};
 canvas.addEventListener('wheel',event=>{event.preventDefault();this.setZoom(this.project.editor.zoom*(event.deltaY<0?1.12:1/1.12),this.toSvgPoint(event));},{passive:false});
 canvas.addEventListener('contextmenu',e=>e.preventDefault());
 canvas.addEventListener('pointerdown',event=>{if(event.button!==0&&event.button!==1)return;if(this.pointerId!=null)finishPointer(true);const point=this.toSvgPoint(event);if(event.button===1||this.tool==='pan'||this.space){beginPointer(event);event.preventDefault();this.pan={x:event.clientX,y:event.clientY,origin:{...this.project.editor.viewCenter},scale:1200/this.project.editor.zoom/canvas.clientWidth};return;}
 const terminal=event.target.closest('[data-terminal]');if(terminal){const key=terminal.dataset.terminal;if(this.pendingTerminal)this.connectTerminals(this.pendingTerminal,key);else{this.pendingTerminal=key;this.onStatus('请选择另一端口完成连接；Esc 取消。');this.render();}return;}
 const handle=event.target.closest('[data-handle]');if(handle){beginPointer(event);this.state.checkpoint();this.wireDrag=handle.dataset.handle;return;}
 const comp=event.target.closest('[data-component]');if(comp){beginPointer(event);const id=comp.dataset.component;if(event.shiftKey){const ids=new Set(this.state.selectedIds);ids.has(id)?ids.delete(id):ids.add(id);this.state.selectedIds=[...ids];}else if(!this.state.selectedIds.includes(id))this.state.selectedIds=[id];this.state.selectedWireId=null;this.onSelect(this.project.components.find(c=>c.id===id));this.drag={start:point,clientStart:{x:event.clientX,y:event.clientY},origins:Object.fromEntries(this.project.components.filter(c=>this.state.selectedIds.includes(c.id)).map(c=>[c.id,{x:c.x,y:c.y}])),saved:false};this.render();return;}
 const wire=event.target.closest('[data-wire]');if(wire){this.state.selectedIds=[];this.state.selectedWireId=wire.dataset.wire;this.render();this.onSelect(null);return;}
 if(catalog[this.tool]){this.add(this.tool,point);return;}beginPointer(event);this.pendingTerminal=null;this.marquee={start:point,current:point,add:event.shiftKey};if(!event.shiftKey)this.state.selectedIds=[];this.state.selectedWireId=null;this.onSelect(null);this.render();});
 window.addEventListener('pointermove',event=>{if(this.pointerId==null||event.pointerId!==this.pointerId)return;if(!(event.buttons&this.pointerButtons)){finishPointer(true);return;}if(this.pan){this.project.editor.viewCenter={x:this.pan.origin.x-(event.clientX-this.pan.x)*this.pan.scale,y:this.pan.origin.y-(event.clientY-this.pan.y)*this.pan.scale};this.render();return;}if(!this.drag&&!this.marquee&&!this.wireDrag)return;const p=this.toSvgPoint(event);if(this.marquee){this.marquee.current=p;this.render();return;}if(this.wireDrag){const w=this.project.wires.find(w=>w.id===this.wireDrag);w.mid=this.snappedWireMid(w,p);this.render();return;}const dx=p.x-this.drag.start.x,dy=p.y-this.drag.start.y;if(!this.drag.saved&&Math.hypot(event.clientX-this.drag.clientStart.x,event.clientY-this.drag.clientStart.y)>4){this.state.checkpoint();this.drag.saved=true;}if(!this.drag.saved)return;for(const [id,o]of Object.entries(this.drag.origins)){const c=this.project.components.find(c=>c.id===id);c.x=o.x+dx;c.y=o.y+dy;}this.render();});
 window.addEventListener('pointerup',event=>{if(event.pointerId===this.pointerId)finishPointer();},true);
 window.addEventListener('pointercancel',event=>{if(event.pointerId===this.pointerId)finishPointer(true);},true);
 canvas.addEventListener('lostpointercapture',event=>{if(event.pointerId===this.pointerId)finishPointer(true);});
 canvas.addEventListener('dragover',e=>e.preventDefault());canvas.addEventListener('drop',e=>{e.preventDefault();const type=e.dataTransfer.getData('component');if(catalog[type])this.add(type,this.toSvgPoint(e));});
 document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,[contenteditable]'))return;const k=e.key.toLowerCase(),ctrl=e.ctrlKey||e.metaKey;if(e.code==='Space'){e.preventDefault();this.space=true;}if(k==='escape'){this.pendingTerminal=null;this.setTool('select');}if(k==='delete'||k==='backspace'){e.preventDefault();this.action('delete');}if(ctrl&&['z','y','c','v','x','a'].includes(k)){e.preventDefault();if(k==='a'){this.state.selectedIds=this.project.components.map(c=>c.id);this.render();}else if(k==='x'){this.state.copy();this.action('delete');}else this.action(k==='z'?(e.shiftKey?'redo':'undo'):({y:'redo',c:'copy',v:'paste'})[k]);}if(!ctrl&&k==='r')this.action('rotate');if(!ctrl&&k==='w')this.setTool('wire');if(!ctrl&&k==='v')this.setTool('select');});document.addEventListener('keyup',e=>{if(e.code==='Space')this.space=false;});window.addEventListener('blur',()=>{this.space=false;finishPointer(true);});new ResizeObserver(()=>this.render()).observe(canvas);
 }
 autoGlue(){const ids=new Set(this.state.selectedIds);for(const c of this.project.components.filter(c=>ids.has(c.id)))for(const [side,domain]of Object.entries(catalog[c.type].ports)){const key=c.id+'.'+side;if(this.project.wires.some(w=>w.from===key||w.to===key))continue;const p=terminalPosition(c,side);let best=null,distance=18;for(const other of this.project.components.filter(c=>!ids.has(c.id)))for(const [s,d]of Object.entries(catalog[other.type].ports)){if(d!==domain)continue;const q=terminalPosition(other,s),dist=Math.hypot(p.x-q.x,p.y-q.y);if(dist<distance){best=other.id+'.'+s;distance=dist;}}if(best)this.project.wires.push({id:this.state.id('W'),from:key,to:best,mid:null});}}
}
