import {prepareResonance,localResonance,sweepResonance} from '../analysis/resonance.js?v=resonance3';
import {rcDesignCandidates} from '../analysis/rc-filter.js?v=pq1';
import {escapeHtml as esc} from './symbols.js?v=transformer-rx3';
const fmt=v=>v===Infinity?'∞':Number.isFinite(v)?Number(v.toPrecision(6)).toLocaleString('en-US',{maximumFractionDigits:7}):'—';
const row=(k,v)=>`<div class="metric-row"><span>${k}</span><b>${v}</b></div>`;
export function resonanceSummary(project,c){
 try{const candidates=rcDesignCandidates(project,c.id),id=c.extensions?.resonance?.ibrId||(candidates.length===1?candidates[0].id:null);if(!id)return '<div class="note">局部 LC 固有频率：请在谐振分析中选择同节点逆变器。</div>';
 const r=localResonance(project,c.id,id);return row('局部 LC 固有频率',fmt(r.frequencyHz)+' Hz');}catch{return '<div class="note">局部 LC 固有频率：需要同节点逆变器及正值 L、C。</div>';}
}
export function mountResonance(host,project,c,save){
 const candidates=rcDesignCandidates(project,c.id),settings={minHz:1,maxHz:20000,ibrId:candidates.length===1?candidates[0].id:'',...c.extensions?.resonance};
 host.innerHTML=`<div class="filter-design-grid resonance-grid"><section><h3>01 · 局部 LC 固有频率</h3><p class="help-label">选定逆变器滤波电感 + 本 RC 电容。仅使用拓扑已应用参数。</p><label class="field"><span>关联逆变器（同一交流节点）</span><select data-res="ibrId" aria-label="谐振分析关联逆变器"><option value="">请选择</option>${candidates.map(i=>`<option value="${esc(i.id)}">${esc(i.name)} · ${esc(i.id)}</option>`).join('')}</select></label><div data-res-local></div><p class="help-label">局部计算移除外部电网，仅保留选定 L 与本 RC 支路；固有频率由 L、C 决定。总串联电阻影响阻尼，自由振荡频率与阻抗峰值频率是不同指标。</p></section>
 <section class="resonance-network"><h3>02 · 全网阻抗扫频</h3><p class="help-label">观察点：${esc(c.name)} 的 AC 接入节点 · 每相正序驱动点阻抗</p><div class="resonance-range"><label class="field"><span>扫频下限</span><div class="field-input"><input data-res="minHz" aria-label="谐振扫频下限" type="number" step="any" min="0" value="${esc(String(settings.minHz))}"><small>Hz</small></div></label><label class="field"><span>扫频上限</span><div class="field-input"><input data-res="maxHz" aria-label="谐振扫频上限" type="number" step="any" min="0" value="${esc(String(settings.maxHz))}"><small>Hz</small></div></label></div>
 <p class="help-label">向观察点注入 1 A 小信号：Y(f) · V(f) = I，Z(f) = V观察点 / 1 A。连接网络内的理想电压源置零；各逆变器保留 Rf/Lf，RC 保留串联阻尼，变压器保留变比及漏阻抗。阻抗全部折算至观察点。</p><div data-res-network></div></section>
 <section class="resonance-plot"><h3>03 · 频率响应与峰值</h3><p class="help-label">横轴为对数频率，阻抗幅值为对数纵轴。悬停曲线区域读取数值；峰值按钮可用键盘聚焦并定位。虚线标记局部 LC 固有频率。</p><div data-res-chart></div><div data-res-readout class="pwm-summary" aria-live="polite"></div><div data-res-peaks class="resonance-peaks"></div><p class="help-label">显示当前扫频范围内可分辨的阻抗局部极大值，并在候选峰附近细化。未检出峰不代表全系统没有谐振；极窄峰、范围外峰以及在该节点不明显的模式可能遗漏。该模型不包含 PI、PLL、控制延迟、磁饱和或频变损耗，不能用于判定闭环稳定性。P/Q 不直接改变固定 R/L/C 的固有频率。</p><details><summary>参与计算的元件与折算参数</summary><div data-res-components></div></details></section></div>`;
 const select=host.querySelector('[data-res="ibrId"]');select.value=settings.ibrId;
 let model;try{model=prepareResonance(project,c.id);}catch(e){model={error:e.message};}
 const inputs=[...host.querySelectorAll('[data-res]')],chart=host.querySelector('[data-res-chart]'),readout=host.querySelector('[data-res-readout]'),peaks=host.querySelector('[data-res-peaks]');
 const read=()=>({ibrId:select.value,minHz:host.querySelector('[data-res="minHz"]').valueAsNumber,maxHz:host.querySelector('[data-res="maxHz"]').valueAsNumber});
 function update(){
  const values=read();let local=null;const localHost=host.querySelector('[data-res-local]');
  try{local=localResonance(project,c.id,values.ibrId);localHost.innerHTML=row('滤波电感 Lf',fmt(local.L*1e3)+' mH')+row('每相电容 Cf',fmt(local.C*1e6)+' μF')+`<div class="resonance-value">${fmt(local.frequencyHz)} <small>Hz</small></div><div class="resonance-equation"><math display="block"><msub><mi>f</mi><mtext>LC</mtext></msub><mo>=</mo><mfrac><mn>1</mn><mrow><mn>2</mn><mi>π</mi><msqrt><msub title="Lf = ${fmt(local.L*1e3)} mH"><mi>L</mi><mi>f</mi></msub><msub title="Cf = ${fmt(local.C*1e6)} μF"><mi>C</mi><mi>f</mi></msub></msqrt></mrow></mfrac></math></div><p class="help-label">1 / [2π √(${fmt(local.L)} H × ${fmt(local.C)} F)] = ${fmt(local.frequencyHz)} Hz</p>`+row('总串联电阻 Rd + Rf',fmt(local.R)+' Ω')+row('局部品质因数 Q',fmt(local.qualityFactor))+row('阻尼比 ζ = R/2 · √(C/L)',fmt(local.dampingRatio))+row('阻尼自由振荡频率',local.dampedHz==null?'非振荡（临界或过阻尼）':fmt(local.dampedHz)+' Hz');}
  catch(e){localHost.innerHTML='<div class="note">'+esc(e.message)+'</div>';}
  const network=host.querySelector('[data-res-network]');
  try{
   if(model.error)throw Error(model.error);const result=sweepResonance(model,values);
   inputs.filter(i=>i.type==='number').forEach(i=>i.removeAttribute('aria-invalid'));
   network.innerHTML=row('参与元件 / 独立节点',model.components.length+' / '+model.size)+row('扫频范围',fmt(values.minHz)+' – '+fmt(values.maxHz)+' Hz')+row('检出阻抗峰',String(result.peaks.length))+(result.peaks.length?row('最高阻抗峰的频率',fmt(result.peaks.reduce((a,b)=>a.magnitude>b.magnitude?a:b).frequencyHz)+' Hz'):'')+`<div class="note ${result.singularCount?'error':''}">${model.clamped?'观察点被理想电压源直接钳位，驱动点阻抗为 0；该观察点无法显示电压谐振峰。':result.singularCount?'部分频点出现无阻尼极点或矩阵病态；曲线在不可计算处断开，请结合阻尼及拓扑判断。':result.peaks.length?'已计算含阻尼的网络响应；峰值不等同于局部 LC 固有频率。':'当前范围未检出可分辨的阻抗峰；可扩大或缩小范围进一步查看。'}</div>`;
   host.querySelector('[data-res-components]').innerHTML='<div class="resonance-table"><table><thead><tr><th>元件</th><th>折算 R / Ω</th><th>折算 L / mH</th><th>折算 C / μF</th><th>阻抗折算倍数</th></tr></thead><tbody>'+model.components.map(x=>`<tr><td>${esc(x.name)} · ${esc(x.id)}${x.type==='source'?'（电压源置零）':x.type==='gfl'||x.type==='gfm'?'（Rf/Lf）':''}</td><td>${fmt(x.R)}</td><td>${fmt(x.L==null?null:x.L*1e3)}</td><td>${fmt(x.C==null?null:x.C*1e6)}</td><td>${fmt(x.factor)}</td></tr>`).join('')+'</tbody></table></div>';
   drawResponse(chart,result,local?.frequencyHz,show);
   function show(p){readout.textContent=p.singular?`${fmt(p.frequencyHz)} Hz · 无阻尼极点或数值病态`:`${fmt(p.frequencyHz)} Hz · |Z| = ${fmt(p.magnitude)} Ω · 相角 = ${p.phaseDeg==null?'未定义':fmt(p.phaseDeg)+'°'} · Z = ${fmt(p.re)} ${p.im<0?'−':'+'} j${fmt(Math.abs(p.im))} Ω`;const line=chart.querySelector('[data-res-cursor]');if(line){const x=60+840*Math.log(p.frequencyHz/result.minHz)/Math.log(result.maxHz/result.minHz);line.setAttribute('x1',x);line.setAttribute('x2',x);line.style.display='';}}
   peaks.innerHTML=result.peaks.length?result.peaks.map((p,i)=>`<button class="contribution" data-res-peak="${i}">峰 ${i+1} · ${fmt(p.frequencyHz)} Hz · ${p.singular?'极点 / 病态':fmt(p.magnitude)+' Ω'}</button>`).join(''):'<span class="help-label">本范围内无可分辨阻抗峰。</span>';
   peaks.querySelectorAll('button').forEach(b=>{b.onclick=b.onfocus=()=>show(result.peaks[Number(b.dataset.resPeak)]);});show(result.peaks[0]||result.samples[Math.floor(result.samples.length/2)]);
   return true;
  }catch(e){network.innerHTML='<div class="note error">'+esc(e.message)+'</div>';chart.innerHTML='';readout.textContent='';peaks.innerHTML='';host.querySelector('[data-res-components]').innerHTML='';if(!model.error)inputs.filter(i=>i.type==='number').forEach(i=>i.setAttribute('aria-invalid','true'));return false;}
 }
 inputs.forEach(input=>{input.oninput=update;input.onchange=()=>{if(update())save(read());};});update();
}
function drawResponse(host,result,localHz,onRead){
 const {minHz,maxHz}=result,samples=[...result.samples,...result.peaks].sort((a,b)=>a.frequencyHz-b.frequencyHz),finite=samples.filter(p=>!p.singular&&p.magnitude>0),logs=finite.map(p=>Math.log10(p.magnitude));
 let lo=logs.length?Math.floor(Math.min(...logs)):-3,hi=logs.length?Math.ceil(Math.max(...logs)):0;if(hi<=lo)hi=lo+1;
 const x=f=>60+840*Math.log(f/minHz)/Math.log(maxHz/minHz),y=z=>210-180*(Math.log10(z)-lo)/(hi-lo),phase=p=>330-p/180*55;
 const path=(getY)=>samples.map((p,i)=>p.singular||!Number.isFinite(getY(p))?'':`${i===0||samples[i-1].singular||!Number.isFinite(getY(samples[i-1]))?'M':'L'}${x(p.frequencyHz).toFixed(2)},${getY(p).toFixed(2)}`).join(' ');
 let grid='';for(let i=0;i<=4;i++){const value=lo+(hi-lo)*i/4,yy=210-i*45;grid+=`<line x1="60" x2="900" y1="${yy}" y2="${yy}" stroke="#e0e9ec"/><text x="52" y="${yy+4}" text-anchor="end">${fmt(10**value)}</text>`;}
 for(let i=0;i<=6;i++){const f=minHz*(maxHz/minHz)**(i/6),xx=x(f);grid+=`<line x1="${xx}" x2="${xx}" y1="30" y2="385" stroke="#edf2f4"/><text x="${xx}" y="405" text-anchor="middle">${fmt(f)}</text>`;}
 host.innerHTML=`<svg viewBox="0 0 940 435" role="img" aria-label="RC 接入点全网阻抗幅值和相角随频率变化曲线">${grid}<text x="60" y="18">|Z| / Ω</text><text x="60" y="255">相角 / °</text><text x="900" y="429" text-anchor="end">频率 / Hz（对数）</text>${[-180,0,180].map(v=>`<line x1="60" x2="900" y1="${phase(v)}" y2="${phase(v)}" stroke="#e0e9ec"/><text x="52" y="${phase(v)+4}" text-anchor="end">${v}</text>`).join('')}<path d="${path(p=>y(p.magnitude))}" fill="none" stroke="#087e75" stroke-width="2.2"/><path d="${path(p=>p.phaseDeg==null?NaN:phase(p.phaseDeg))}" fill="none" stroke="#437dac" stroke-width="1.8"/>${localHz>=minHz&&localHz<=maxHz?`<line x1="${x(localHz)}" x2="${x(localHz)}" y1="30" y2="385" stroke="#b17b22" stroke-dasharray="5 4"/><text x="${Math.min(790,x(localHz)+5)}" y="28" fill="#96630b">局部 ${fmt(localHz)} Hz</text>`:''}<line data-res-cursor y1="30" y2="385" stroke="#a94432" stroke-dasharray="2 3" style="display:none"/><rect data-res-hit x="60" y="30" width="840" height="355" fill="transparent"/></svg>`;
 host.querySelector('[data-res-hit]').onpointermove=e=>{const svg=host.querySelector('svg'),rect=svg.getBoundingClientRect(),xx=(e.clientX-rect.left)*940/rect.width,t=Math.max(0,Math.min(1,(xx-60)/840));const f=minHz*(maxHz/minHz)**t;onRead(samples.reduce((a,b)=>Math.abs(Math.log(a.frequencyHz/f))<Math.abs(Math.log(b.frequencyHz/f))?a:b));};
}
